version: "3.7"

services:
  database_learning:
    image: postgres
    container_name: database_learning
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=e-learning
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: e-learning
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_learning
    depends_on: 
      - database_learning


volumes:
  pgdata:
    driver: local